server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s

services:
  user_service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
    timeout: 10s
  
  order_service:
    url: ${ORDER_SERVICE_URL:http://localhost:8082}
    timeout: 10s

logging:
  level: info
  format: json

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://example.com"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization

rate_limiting:
  enabled: true
  requests_per_minute: 100
